id: P1780A596
initial_creation_type: input
source_metadata:
  title: Yukhok Chöying Rangdrol Series
  language: bo
  description: 'Texts by Yukhok Chatralwa Chöying Rangdrol (g.yu khog bya bral ba
    chos dbyings rang grol, 1872–1952), including extracts from his Ngöndro Compendium,
    a commentary on the Longchen Nyingtik preliminary practices:'
  volume:
    66ecf894d8bf4b93b8731b8e4668a4e3:
      title: Advice to Damngak Gyatso of Do
      parent: Advice
    2c587a3a78c7464abe3fb0f14b64ecbd:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    32826c64b60d4641a3d71bf1acf36117:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Dzogchen
    f19bcd26be3e443b8907b0a57c8ea2ee:
      title: Commentary on Vajra Verses on the Natural State
      parent: Dzogchen
    c93d351f9fe64754b82225f366a187a4:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Dzogchen
    1ec46fc1072642a1a28cbb7ceee064c8:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Dzogchen
    5a8c0eab6dee4c1b85aba700707cb69b:
      title: Ngöndro Compendium—Part 1—Invoking the Lama
      parent: Ngöndro Compendium
    0484cdad665d46439f1efecb342b687d:
      title: Ngöndro Compendium—Part 2—Taking Refuge
      parent: Ngöndro Compendium
    55adcf23727642e7b251e2518d201376:
      title: Ngöndro Compendium—Part 3—Arousing Bodhichitta
      parent: Ngöndro Compendium
    90406236dd0c4269a25bcd06182239f6:
      title: Ngöndro Compendium—Part 4—Mandala Offering
      parent: Ngöndro Compendium
    c9ebde8f36bc467fa42ee3de16f9fb80:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T02:04:57.174371'
last_modified_at: '2022-03-01T02:04:57.174373'
